modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="${forge_version_range}" #mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT, or SERVER
side="BOTH"
# Here's another dependency

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="paraglider"
mandatory=true
versionRange="[20.1.3]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="epicfight"
mandatory=true
versionRange="[20.9.2]"
ordering="AFTER"
side="BOTH"
